name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint --if-present
      - name: Unit Tests
        run: npm run test
  e2e:
    runs-on: ubuntu-latest
    needs: install-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Start dev server
        run: npm run dev &
      - name: Wait for server
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: 'http://localhost:3000'
          timeout: 30
      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run dev
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 60
        env:
          VITE_SUPABASE_URL: ${{ https://jfxcvepfrixbwhpfuitj.supabase.co }}
          VITE_SUPABASE_ANON_KEY: ${{ eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFycGdoamZrcnJhY212anplc2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2OTE1MzksImV4cCI6MjA2NjI2NzUzOX0.LButUVzKjUJP_6WKwrbAjehmVpVgQA9Wi-0CGkuKYno }} 